exports.up = function(knex, Promise) {
  return knex.schema
    .createTable('users', table => {
      table.bigIncrements('user_id');
      table
        .string('username')
        .unique()
        .notNullable();
      table.string('password').notNullable();
      table.string('email');
      table.string('github_token');
      table.bigInteger('created_at').defaultTo(Date.now());
      table.bigInteger('updated_at').defaultTo(Date.now());
    })
    .createTable('documents', table => {
      table.bigIncrements('doc_id');
      table.string('doc_title').notNullable();
      table.string('doc_author').notNullable();
      table
        .integer('kissit_doc_author')
        .references('user_id')
        .inTable('users')
        .onDelete('cascade');
      table.text('doc_contents');
      table.string('doc_url');
      table.bigInteger('created_at').defaultTo(Date.now());
      table.bigInteger('updated_at').defaultTo(Date.now());
    })
    .createTable('user_doc', table => {
      table.bigIncrements('user_doc_id');
      table
        .bigInteger('user_id')
        .references('user_id')
        .inTable('users')
        .onDelete('cascade')
        .notNullable();
      table
        .bigInteger('doc_id')
        .references('doc_id')
        .inTable('documents')
        .onDelete('cascade')
        .notNullable();
    })
    .createTable('user_fav_doc', table => {
      table.bigIncrements('user_fav_doc_id');
      table
        .bigInteger('user_id')
        .references('user_id')
        .inTable('users')
        .onDelete('cascade')
        .notNullable();
      table
        .bigInteger('doc_id')
        .references('doc_id')
        .inTable('documents')
        .onDelete('cascade')
        .notNullable();
      table.bigInteger('date_favorited').defaultTo(Date.now());
    })
    .createTable('user_fav_user', table => {
      table.bigIncrements('user_fav_user_id');
      table
        .bigInteger('user_id')
        .references('user_id')
        .inTable('users')
        .onDelete('cascade')
        .notNullable();
      table
        .bigInteger('fav_user')
        .references('user_id')
        .inTable('users')
        .onDelete('cascade')
        .notNullable();
      table.bigInteger('date_favorited').defaultTo(Date.now());
    })
    .createTable('user_doc_rating', table => {
      table.bigIncrements('user_doc_rating_id');
      table
        .bigInteger('rated_by')
        .references('user_id')
        .inTable('users')
        .onDelete('cascade')
        .notNullable();
      table
        .bigInteger('doc_id')
        .references('doc_id')
        .inTable('documents')
        .onDelete('cascade')
        .notNullable();
      table.integer('doc_rating').notNullable();
      table.bigInteger('date_rated').defaultTo(Date.now());
    })
    .createTable('user_github', table => {
      table.bigIncrements('user_github_id');
      table.string('github_html_url');
      table.string('github_api_url');
      table.integer('number_of_favorites');
      table.integer('number_of_followers');
      table.integer('number_of_repo');
      table.bigInteger('last_github_update').defaultTo(Date.now());
      table.string('github_token');
      table
        .bigInteger('user_id')
        .references('user_id')
        .inTable('users')
        .onDelete('cascade');
    })
    .createTable('following_on_github', table => {
      table.bigIncrements('following_on_github_id');
      table
        .bigInteger('user_github_id')
        .references('user_github_id')
        .inTable('user_github')
        .onDelete('cascade');
      table.string('favorite');
    })
    .createTable('rdf_tree', table => {
      table.bigIncrements('rdf_tree_id');
      table
        .bigInteger('user_github_id')
        .references('user_github_id')
        .inTable('user_github')
        .onDelete('cascade');
      table.bigInteger('last_update').defaultTo(Date.now());
      table.string('url').notNullable();
      table.integer('level').notNullable();
      table.bigInteger('parent_id');
    })
    .createTable('code_files', table => {
      table.bigIncrements('file_id');
      table.string('file_name').notNullable();
      table.string('file_author').notNullable();
      table
        .integer('kissit_file_author')
        .references('user_id')
        .inTable('users')
        .onDelete('cascade');
      table.text('file_html_table');
      table.text('file_code');
      table.text('file_path');
      table.string('file_url');
      table.bigInteger('created_at').defaultTo(Date.now());
      table.bigInteger('updated_at').defaultTo(Date.now());
      table
        .bigInteger('rdf_tree_id')
        .references('rdf_tree_id')
        .inTable('rdf_tree')
        .onDelete('cascade');
    })
    .createTable('user_code_rating', table => {
      table.bigIncrements('user_code_rating_id');
      table
        .bigInteger('rated_by')
        .references('user_id')
        .inTable('users')
        .onDelete('cascade')
        .notNullable();
      table
        .bigInteger('file_id')
        .references('file_id')
        .inTable('code_files')
        .onDelete('cascade')
        .notNullable();
      table.integer('file_rating').notNullable();
      table.bigInteger('date_rated').defaultTo(Date.now());
    })
    .createTable('user_fav_code', table => {
      table.bigIncrements('user_fav_code_id');
      table
        .bigInteger('user_id')
        .references('user_id')
        .inTable('users')
        .onDelete('cascade')
        .notNullable();
      table
        .bigInteger('file_id')
        .references('file_id')
        .inTable('code_files')
        .onDelete('cascade')
        .notNullable();
      table.bigInteger('date_favorited').defaultTo(Date.now());
    });
};

exports.down = function(knex, Promise) {
  return knex.schema
    .dropTable('user_fav_code')
    .dropTable('user_code_rating')
    .dropTable('code_files')
    .dropTable('rdf_tree')
    .dropTable('following_on_github')
    .dropTable('user_github')
    .dropTable('user_doc_rating')
    .dropTable('user_fav_user')
    .dropTable('user_fav_doc')
    .dropTable('user_doc')
    .dropTable('documents')
    .dropTable('users');
};
